export { default as About } from "./About";
export { default as Blog } from "./Blog";
export { default as Contact } from "./Contact";
export { default as Error } from "./Error";
export { default as Features } from "./Features";
export { default as Home } from "./Home";
export { default as SharedLayout } from "./SharedLayout";
export { default as Shop } from "./Shop";
export { default as Product } from "./Product";
